<?php

/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Frame\Demo;

/**
 * Class Test
 * @package Neoan3\Components
 */

class Test extends Demo{
    /**
     * GET: api.v1/test
     * @param $params
     * @return array
     */
    function getTest(array $params=[]): array
    {
        return $params;
    }

    /**
     * POST: api.v1/test
     * @param $body
     * @return array
     */
    function postTest(array $body): array
    {
        return $body;
    }
}
